This is the main notebook for the project. 

Markov Chain Monte Carlo Library: https://github.com/dflemin3/approxposterior

The idea:
Get a random array of binary values to return a True value when passed through a hidden "black box" function. Using a Markov Chain Monte Carlo (MCMC) method, we can find the hidden function.

Input will be a numpy array of binary values. Output will be a boolean value.

Ex: 
- Input: [0, 1, 0, 1, 1, 0, 0, 1, 1, 1]
- Output: False

The hidden function will be a random function that returns True when the input array is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1].

The MCMC method will be used to find the hidden function. The MCMC method will be implemented using the ApproxPosterior library.

In [24]:
from approxposterior import approx, gpUtils, likelihood as lh, utility as ut
import numpy as np

In [27]:
# input array of theta will always be a 10 item numpy array with each element being a 1 or 0

def create_test_data(number_of_samples = 100, length = 10):
    all_observations = []

    for i in range(number_of_samples):
        theta = np.random.randint(2, size=length)
        observation = np.random.randint(2, size=length)
        all_observations.append([theta, observation])

        

In [28]:
test_data = create_test_data()

In [29]:
test_data.shape

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
print('First 10 samples of test data:')
print(test_data[0:10,:])

First 10 samples of test data:
[[1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 1. 1.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0. 1.]]


In [14]:
def black_box_function(theta):
    # theta is a 10 item numpy array with each element being a 1 or 0
    
    # if the item in position 7 is 1, return True, else return False
    if theta[7] == 1:
        return True
    else:
        return False